/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgajosefina;

import java.awt.Point;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Bolivar
 */
public class agregararticulo extends javax.swing.JFrame {
boolean startwriter;
    /**
     * Creates new form agregararticulo
     */
    public agregararticulo(Point p) {
        initComponents();
        setLocation(p);
        setTitle("Agregar Articulo");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtunidades = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtpreciocompra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Nuevo articulo:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Precio de venta:");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jLabel5.setText("Unidades:");

        jButton1.setText("Crear articulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio de compra:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(7, 7, 7)))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre)
                            .addComponent(txtmarca)
                            .addComponent(txtprecio)
                            .addComponent(txtunidades)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtpreciocompra)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtpreciocompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gestionarticulos go=new gestionarticulos(this.getLocation());
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed
public boolean comprobarexistencia(){


    String registro="";
        String nombre="";
        String marca="";
        boolean comprueba=true;
        
        // cargado el combo box
        try{
          FileReader leer=new FileReader("datos/articulos.data");
       BufferedReader contenido=new BufferedReader(leer);
       
       
       registro=contenido.readLine();
       
       while(registro!=null){
              

  
    
        
           for(int i=0;i<registro.length();i++){
           // lee nombre articulo
               if(registro.charAt(i)=='#'){
               
                   for(int j=i+1;registro.charAt(j)!='$';j++){
                   nombre+=registro.charAt(j);
                   } 
                
           
              }
               
                // lee marca articulo
               if(registro.charAt(i)=='$'){
               
                   for(int j=i+1;registro.charAt(j)!='%';j++){
                   marca+=registro.charAt(j);
                   } 
           
              }
               
            
               
               if(nombre.equals(txtnombre.getText())&& marca.equals(txtmarca.getText()))comprueba=false;
                
               
           }
           
        
              
                  registro="";
                  nombre="";
                  marca="";
                  registro=contenido.readLine();
  
                  
       }
       
       //cerrando el flujo de lectura
       leer.close();
       contenido.close();
 
      
        }catch(Exception e){
        
            
        
        }
    
    
    
    
    
return comprueba;
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if(comprobarexistencia()){
        
        try{
        //agregando articulo
        FileWriter fw=new FileWriter("datos/articulos.data",true);




/*
        lectura sin utilidad
        FileReader leer=new FileReader("datos/articulos.txt");
       BufferedReader contenido=new BufferedReader(leer);
*/
       fw.write("\r\n");
       
    
       /*
       while(contenido.readLine()!=null){
        fw.write("\r\n");
System.out.println("X");
        }
*/


        //escribiendo nombre

        try{

fw.write('#');
for(int i=0;i<txtnombre.getText().length();i++){

fw.write(txtnombre.getText().charAt(i));
}



}catch(IOException e){
}
        
                //escribiendo marca
        try{

fw.write('$');
for(int i=0;i<txtmarca.getText().length();i++){

fw.write(txtmarca.getText().charAt(i));
}



}catch(IOException e){
}
        
                   //escribiendo precio
        try{
Double.parseDouble(txtprecio.getText());
fw.write('%');
for(int i=0;i<txtprecio.getText().length();i++){

fw.write(txtprecio.getText().charAt(i));
}

}catch(IOException e){
    JOptionPane.showMessageDialog(null,"Solo ingrese datos numericos en precio");
}
  
                        //escribiendo unidades
        try{
Integer.parseInt(txtunidades.getText());
fw.write('@');
for(int i=0;i<txtunidades.getText().length();i++){

fw.write(txtunidades.getText().charAt(i));
}



}catch(IOException e){
    JOptionPane.showMessageDialog(null,"Solo ingrese numeros enteros en unidades");
}
      
        
        
                                //escribiendo precio compra
        try{
Double.parseDouble(txtpreciocompra.getText());
fw.write('!');
for(int i=0;i<txtpreciocompra.getText().length();i++){

fw.write(txtpreciocompra.getText().charAt(i));
}



}catch(IOException e){
    JOptionPane.showMessageDialog(null,"Solo ingrese datos numericos en precio de compra");
}
        
        
        

//close file
    JOptionPane.showMessageDialog(null,"Articulo: ("+txtnombre.getText()+") ("+txtmarca.getText()+") creado!");
    fw.close();
 

        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,"No se encontro el  archivo articulo.data");
        }
        
        }else{
        
        JOptionPane.showMessageDialog(null,"El articulo: "+txtnombre.getText()+" ("+txtmarca.getText()+") ya existe!","Articulo existente",JOptionPane.ERROR_MESSAGE);
        
        }
        
        
        //aqui corta
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtpreciocompra;
    private javax.swing.JTextField txtunidades;
    // End of variables declaration//GEN-END:variables
}
