/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgajosefina;

import java.awt.Point;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.OutputStreamWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Bolivar
 */
public class ajustes extends javax.swing.JFrame {

    /**
     * Creates new form ajustes
     */
    public ajustes(Point p) {
        initComponents();
        setLocation(p);
        setTitle("Ajustes");
        setResizable(false);
        if(frame1.getrango().equals("500")){
        
        jButton2.setEnabled(false);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pas1 = new javax.swing.JPasswordField();
        pas2 = new javax.swing.JPasswordField();
        pas3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText(frame1.getusername());

        jLabel3.setText("Cambiar contraseña->");

        jLabel4.setText("Contraseña actual:");

        jLabel5.setText("Nueva contraseña:");

        jLabel6.setText("Confirme contraseña:");

        jButton1.setText("Cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pas2)
                                    .addComponent(pas3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(pas1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addComponent(pas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 String registro[]=new String[100];
 String nombre="";
 String marca="";
 String precio="";
 String unidades="";
 String registroc="";
 String contra1=new String(pas1.getPassword());
 String contra2=new String(pas2.getPassword());
 String contra3=new String(pas3.getPassword());
 
 
 int desde=0;
 int hasta=0;
 int registros=0;
 boolean corresponde=false;
        
        if(contra1.equals(frame1.getpass())){
        
           if(contra2.equals(contra3) && !contra2.equals("")){
               
               
               // lectura comprobacion
               
               try{
               
                      
        FileReader leer=new FileReader("datos/sfx.data");
       BufferedReader contenido=new BufferedReader(leer);
       
   
      
 


             registro[registros]=contenido.readLine(); //lee la primera linea en blanco
             registros++;
             registroc=contenido.readLine();
     
    
             System.out.println(registroc);
             
             while(registroc!=null){
                       
            
             for(int i=0;i<registroc.length();i++){
               
               
                 if(registroc.charAt(i)=='#'){
                 
                 for(int j=i+1;registroc.charAt(j)!='$';j++){
                 nombre+=registroc.charAt(j);
                 
                 }
             
                 
                 
                 }
                 
                    // lee marca articulo
               if(registroc.charAt(i)=='$'){
                   
               
                 
                   for(int j=i+1;registroc.charAt(j)!='%';j++){
                   marca+=registroc.charAt(j);
                   } 
              
              }
                
             if((nombre.equals(frame1.getusername())) && (marca.equals(frame1.getpass())) && corresponde==false)
             {
             corresponde=true;
            
               
             }
             
                  // lee precio del articulo
               if(registroc.charAt(i)=='%'){
           
                   for(int j=i;registroc.charAt(j)!='@';j++){
                   precio+=registroc.charAt(j);
                   } 
             
              }
          

           
             // lee unidades
                if(registroc.charAt(i)=='@'){
               
                   for(int j=i;j<registroc.length();j++){
                   unidades+=registroc.charAt(j);
                   } 

              }
           
           
           }
          
             if(corresponde){
                 // cambia password
           
            registroc=registroc.replaceAll(marca,contra3);


          
               corresponde=false;
               
               
             }
       
                 registro[registros]=registroc;
   
         
           
                  registros++;
                  
                  
   
                  registroc=contenido.readLine();
  
                  nombre="";
                  precio="";
                  marca="";
                  unidades="";
       
                 
                             
             }
        
             
             leer.close();
   contenido.close();
               
   
   // modificacion de registros
         File fout = new File("datos/sfx.data");
FileOutputStream fos = new FileOutputStream(fout);

BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fos));

   for(int i=0;i<registros;i++){
   bw.write(registro[i]);
    
       
       if(i==registros-1)
       {
           break;
       }
   bw.newLine();
   }
             
            bw.close();  
             fos.close();
             
             JOptionPane.showMessageDialog(null,"Contraseña cambiada!");
   
               }catch(Exception e){
               
               
               System.out.println("Error al cambiar");
               }
               
               
               
               
               
               
           
           
           }else{
           
               JOptionPane.showMessageDialog(null,"Error al confimar la contraseña");
               
               
           }       
        
        }else{
        
        JOptionPane.showMessageDialog(null,"Contraseña actual incorrecta");
        
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        

        agregarusuario go=new agregarusuario(this.getLocation()); 
go.setVisible(true);
this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu go=new Menu(this.getLocation());
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pas1;
    private javax.swing.JPasswordField pas2;
    private javax.swing.JPasswordField pas3;
    // End of variables declaration//GEN-END:variables
}
