/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgajosefina;

import java.awt.Point;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Bolivar
 */
public class consultafactura extends javax.swing.JFrame {

    /**
     * Creates new form consultafactura
     */
    public consultafactura(Point p) {
        initComponents();
        setLocation(p);
        setTitle("Consulta factura");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnofactura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbarticulosvendidos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbmontototal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbganancias = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonfecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No. FACTURA:");

        jLabel2.setText("<Articulos vendidos>");

        lbarticulosvendidos.setText("--------------------------------------------------------------------------------------------------------");

        jLabel4.setText("<Monto total>");

        lbmontototal.setText("-------------------------------------------------------------------------------------------------------");

        jLabel6.setText("<Ganancias>");

        lbganancias.setText("-------------------------------------------------------------------------------------------------------");

        jLabel8.setText("<Fecha>");

        lbfecha.setText("--------------------------------------------------------------------------------------------------------");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botonfecha.setText("Detalles fecha");
        botonfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbarticulosvendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnofactura, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton1)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbfecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbganancias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbmontototal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnofactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbarticulosvendidos)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbmontototal)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbganancias)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addComponent(lbfecha)
                .addGap(18, 18, 18)
                .addComponent(botonfecha)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String preciocompra="";
String fechacortas="";
String fechadetalles="";
boolean encontrado;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String registro="";
String nombre="";
String marca="";
String precio="";
String unidades="";
preciocompra="";
fechacortas="";



 encontrado=false;
        
        
            try{
            
         FileReader leer=new FileReader("datos/stf.data");
       BufferedReader contenido=new BufferedReader(leer);
              registro=contenido.readLine();
              

              
           while(registro!=null){
               
              for(int i=0;i<registro.length();i++){
                  
           // lee numero factura
               if(registro.charAt(i)=='#'){
               
                   for(int j=i+1;registro.charAt(j)!='$';j++){
                   nombre+=registro.charAt(j);
                 
                   } 
                
           
              }
               
                // lee marca articulo (articulos vendidos)
               if(registro.charAt(i)=='$'){
               
                   for(int j=i+1;registro.charAt(j)!='%';j++){
                   marca+=registro.charAt(j);
                   } 
           
              }
               
                 // lee precio del articulo (monto total)
               if(registro.charAt(i)=='%'){
               
                   for(int j=i+1;registro.charAt(j)!='@';j++){
                   precio+=registro.charAt(j);
                   } 
           
              }
               // lee unidades (ganancia)
                if(registro.charAt(i)=='@'){
               
                   for(int j=i+1;registro.charAt(j)!='*';j++){
                   unidades+=registro.charAt(j);
                   } 
           
              }
                
                  // lee precio bruto (fecha)
                if(registro.charAt(i)=='*'){
               
                   for(int j=i+1;registro.charAt(j)!='&';j++){
                   preciocompra+=registro.charAt(j);
                   } 
           
              }
                
                 // lee fecha corta
                if(registro.charAt(i)=='&'){
               
                   for(int j=i+1;j<registro.length();j++){
                   fechacortas+=registro.charAt(j);
                   } 
           
              }
                
                
               
           }
           
         
   
        if(nombre.equals("FACT"+txtnofactura.getText())){
        
      lbarticulosvendidos.setText(marca);
      lbmontototal.setText(precio);
      lbganancias.setText(unidades);
      lbfecha.setText(fechacortas);
      fechadetalles=preciocompra;
     
      /*
      Date date=new Date(preciocompra);
      */
      
      encontrado=true;
      
         
        
        }
              
                  registro="";
                  nombre="";
                  precio="";
                  marca="";
                  unidades="";
                  preciocompra="";
                  fechacortas="";
                  registro=contenido.readLine();

                  
       }
           
           
           
           
   leer.close();
   contenido.close();
   
   if(!encontrado){
   
   JOptionPane.showMessageDialog(null,"Factura no encontrada!","Not found",JOptionPane.ERROR_MESSAGE);
        lbarticulosvendidos.setText("----------------------------------------------");
      lbmontototal.setText("----------------------------------------------");
      lbganancias.setText("----------------------------------------------");
      lbfecha.setText("----------------------------------------------");
   
   }
       
        }catch(Exception e){
        
        
        
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu go=new Menu(this.getLocation());
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfechaActionPerformed
        // TODO add your handling code here:
        
           if(encontrado){
            
       lbfecha.setText(fechadetalles);

        
        }
        
        
    }//GEN-LAST:event_botonfechaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonfecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbarticulosvendidos;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbganancias;
    private javax.swing.JLabel lbmontototal;
    private javax.swing.JTextField txtnofactura;
    // End of variables declaration//GEN-END:variables
}
