/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgajosefina;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.imageio.ImageIO;
import javax.swing.*;
/**
 *
 * @author Bolivar
 */
public class frame1 extends javax.swing.JFrame {
    private static String iusername;
    private static String ipass;
    private static String rango;
    

    /**
     * Creates new form frame1
     */
    public frame1() {
       
        initComponents();
         setTitle("SGA Josefina");
        jPanel1.add(new fondo(this.getWidth(),this.getHeight()));
        setResizable(false);

        

    }
    
   public static String getusername(){
   
       return iusername;
   }
    public static String getpass(){
    return ipass;
    }

    public static String getrango(){
    return rango;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 String pass=new String(txtpassword.getPassword());
        if(txtusuario.getText().equals("thunderbelt") && pass.equals("alfalgata07")){
            //validacion master
             Menu start=new Menu(this.getLocation());
        start.setVisible(true);
        this.dispose();
        
        }else{
        
        // otra validacion
            
 String username="";
 String password="";
 String precio="";
 String unidades="";
 String registroc="";
 int p=0;
 int desde=0;
 int hasta=0;
 boolean corresponde=false;
        try{
            
        FileReader leer=new FileReader("datos/sfx.data");
       BufferedReader contenido=new BufferedReader(leer);
       
   
      
 


     

             registroc=contenido.readLine();
     
    
             System.out.println(registroc);
             
             while(registroc!=null){
                       

             for(int i=0;i<registroc.length();i++){
               
               //lee username
                 if(registroc.charAt(i)=='#'){
                 
                 for(int j=i+1;registroc.charAt(j)!='$';j++){
                 username+=registroc.charAt(j);
                 
                 }
             
                 
                 
                 }
                 
                    // lee password
               if(registroc.charAt(i)=='$'){
                   
               
                 
                   for(int j=i+1;registroc.charAt(j)!='%';j++){
                   password+=registroc.charAt(j);
                   } 
              
              }
                
             if((username.equals(txtusuario.getText())) && (password.equals(pass)) && corresponde==false)
             {
             corresponde=true;
            
               
             }

                  // lee precio del articulo
               if(registroc.charAt(i)=='%'){
           
                   for(int j=i;registroc.charAt(j)!='@';j++){
                   precio+=registroc.charAt(j);
              
                   } 
             
              }
          

           
             // lee unidades
                if(registroc.charAt(i)=='@'){
               
                   for(int j=i;j<registroc.length();j++){
                   unidades+=registroc.charAt(j);
                   } 

              }
           
           
           }
          
             if(corresponde){
         // credenciales correctas
                      iusername=username;
                      ipass=password;
                      rango=precio.replaceAll("%","");
             leer.close();
              contenido.close();
              corresponde=false;
               Menu start=new Menu(this.getLocation());
        start.setVisible(true);
        this.dispose();
          
    
               
             }
       

   
         
                  
                  
   
                  registroc=contenido.readLine();
  
                  username="";
                  precio="";
                  password="";
                  unidades="";
       
                 
                             
             }
        
             
             leer.close();
   contenido.close();
   JOptionPane.showMessageDialog(null,"Nombre de usuario o contraseña incorrecta","Credenciales invalidas",JOptionPane.ERROR_MESSAGE);
   
        }
   catch (Exception e){
           
           
           }         
        
        
        
            
            
            
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}

class fondo extends JPanel{

public fondo(int widht, int height){

setSize(widht,height);



}


public void paintComponent(Graphics g){

try{
File imagen=new File("datos/login4.png");
Image i=ImageIO.read(imagen);

 g.drawImage(i, 0, 0, this.getWidth(),this.getHeight(), null);
}catch(Exception e){



}
}


}